version: '3.8'

services:
  receipt-processor:
    build: .
    container_name: receipt-processor-container
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
